version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: "Etc/UTC"

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: "Etc/UTC"

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: "Etc/UTC"
