name: krivostr-core
version: 0.3.0.0
github: sagar-shirwalkar/krivostr
license: AGPL-3.0-only
author: you
maintainer: you@example.com
category: Network

dependencies:
  - base >= 4.19 && < 5
  - aeson >= 2.2
  - bytestring
  - text
  - containers
  - mtl
  - time
  - base16-bytestring
  - cryptohash-sha256
  - memory
  - bech32
  - transformers
  - scientific
  - stm

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - krivostr-core
      - hspec
      - QuickCheck
      - aeson
    ghc-options: [-threaded]
