name: zap
on:
  pull_request:
    paths:
      - 'client/**'
      - 'docker/**'

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

      - name: Start the bridge
        run: |
          docker build -f docker/Dockerfile.linux --target build -t krivostr:zap .
          docker run -d --name krivostr-zap -p 8081:8081 krivostr:zap
          sleep 5  # give it time to bind

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@7c4deb10e6261301961c86d65d54a516394f9aed  # v0.14.0
        with:
          target: 'http://localhost:8081'
          fail_action: true
          allow_issue_writing: false

      - name: Stop the bridge
        if: always()
        run: docker stop krivostr-zap
